from astropy.io import fits
from astropy import wcs
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import coordinates
import matplotlib.colors as colors
from visualization import make_scalebar
from constants import distance
from mpl_plot_templates import asinh_norm
import matplotlib.gridspec as gridspec
from matplotlib.colors import LogNorm
from matplotlib.colors import PowerNorm
import matplotlib.colors as colors
import matplotlib.patches as patches
from astropy.table import Table
import matplotlib.patheffects as PathEffects
from matplotlib.ticker import *
from astropy.visualization import make_lupton_rgb
import numpy as np

from matplotlib.patches import ConnectionPatch
from mpl_plot_templates import asinh_norm
import pandas as pd


def polygon_reader(regfile):
    '''Read in *.reg file, in DS9 format. Convert the single-line
    polygon description to a set of sets of points pairs / geo.Polygon
    Args: 
        regfile: the input region file, should contains polygon description
            generated by ds9.
    Returns:
        list of shapely.geometry.Polygon()s.
    '''
    f = open(regfile, 'r')
    poly_list = []
    for line in f:
        if 'polygon(' in line:
            single_line_poly = line[line.find('(') + 1:line.find(')')]
            single_line_poly = np.array(list(map(float,
                                                 single_line_poly.split(','))))
            # print(single_line_poly)
            poly_x = single_line_poly[0::2]
            poly_y = single_line_poly[1::2]
            poly_list.append((np.array([poly_x, poly_y]).T))
    return poly_list


def plotcores(ax, coresa, coresb, linewidth=1):
    num = 0
    bnum = 0
    xlim = ax.get_xlim()
    ylim = ax.get_ylim()
    for i in range(len(coresa['x_img'])):
        within = True
        within = coresa['x_img'][i] > xlim[0] and within
        within = coresa['x_img'][i] < xlim[1] and within
        within = coresa['y_img'][i] > ylim[0] and within
        within = coresa['y_img'][i] < ylim[1] and within
        if within:
            num = num + 1
            if 1:  # coresa['em'][i] > 1e7:
                bnum = bnum + 1
                e1 = patches.Ellipse((coresa['x_img'][i], coresa['y_img'][i]),
                                     coresa['r_img'][i] *
                                     2, coresa['r_img'][i] * 2,
                                     angle=0,
                                     linewidth=linewidth,
                                     fill=False, zorder=30,
                                     edgecolor=(1, 1, 1.0, 1.0),
                                     # facecolor=(1, 1, 0.0, 0.8),
                                     path_effects=[PathEffects.withStroke(linewidth=linewidth * 1.5,
                                                                          foreground="b")])
                # ax.add_patch(e1)
            else:
                e1 = patches.Ellipse((coresa['x_img'][i], coresa['y_img'][i]),
                                     coresa['r_img'][i] *
                                     2, coresa['r_img'][i] * 2,
                                     angle=0,
                                     linewidth=linewidth,
                                     fill=False, zorder=30,
                                     edgecolor=(1, 1, 1.0, 1.0),
                                     # facecolor=(1, 1, 0.0, 0.8),
                                     path_effects=[PathEffects.withStroke(linewidth=linewidth * 1.5,
                                                                          foreground="b")])

                ax.add_patch(e1)

    # for i in range(len(coresb['x_img'])):
    #     within = True
    #     within = coresb['x_img'][i] > xlim[0] and within
    #     within = coresb['x_img'][i] < xlim[1] and within
    #     within = coresb['y_img'][i] > ylim[0] and within
    #     within = coresb['y_img'][i] < ylim[1] and within
    #     if within:
    #         e1 = patches.Ellipse((coresb['x_img'][i], coresb['y_img'][i]),
    #                              coresb['ella'][i] * 2, coresb['ellb'][i] * 2,
    #                              angle=coresb['ellt'][i],
    #                              linewidth=linewidth / 2,
    #                              fill=False, zorder=3,
    #                              edgecolor=(0.3, 0.3, 0.3, 0.3),
    #                              # facecolor=(1, 1, 0.0, 0.8),
    #                              path_effects=[PathEffects.withStroke(linewidth=linewidth * 0.5,
    #                                                                   foreground="w")])

    #         ax.add_patch(e1)
    return num, bnum


def plotcores_G95(ax, coresa, coresb, linewidth=1):
    num = 0
    bnum = 0
    xlim = ax.get_xlim()
    ylim = ax.get_ylim()
    for i in range(len(coresa['G95_X'])):
        within = True
        within = coresa['G95_X'][i] > xlim[0] and within
        within = coresa['G95_X'][i] < xlim[1] and within
        within = coresa['G95_Y'][i] > ylim[0] and within
        within = coresa['G95_Y'][i] < ylim[1] and within
        if within:
            num = num + 1
            if 1:  # coresa['em'][i] > 1e7:
                bnum = bnum + 1
                e1 = patches.Ellipse((coresa['G95_X'][i], coresa['G95_Y'][i]),
                                     coresa['G95_A'][i] *
                                     2, coresa['G95_B'][i] * 2,
                                     angle=coresa['G95_T'][i],
                                     linewidth=linewidth,
                                     fill=False, zorder=31,
                                     edgecolor=(1, 0.4, 0.4, 0.8),
                                     # facecolor=(1, 1, 0.0, 0.8),
                                     path_effects=[PathEffects.withStroke(linewidth=linewidth * 1.5,
                                                                          foreground="w")])
                ax.add_patch(e1)
            else:
                e1 = patches.Ellipse((coresa['G95_X'][i], coresa['G95_Y'][i]),
                                     coresa['G95_A'][i] *
                                     2, coresa['G95_B'][i] * 2,
                                     angle=coresa['G95_T'][i],
                                     linewidth=linewidth,
                                     fill=False, zorder=30,
                                     edgecolor=(1, 1, 1.0, 1.0),
                                     # facecolor=(1, 1, 0.0, 0.8),
                                     path_effects=[PathEffects.withStroke(linewidth=linewidth * 1.5,
                                                                          foreground="b")])

                ax.add_patch(e1)

    # for i in range(len(coresb['X_IMAGE'])):
    #     within = True
    #     within = coresb['X_IMAGE'][i] > xlim[0] and within
    #     within = coresb['X_IMAGE'][i] < xlim[1] and within
    #     within = coresb['Y_IMAGE'][i] > ylim[0] and within
    #     within = coresb['Y_IMAGE'][i] < ylim[1] and within
    #     if within:
    #         e1 = patches.Ellipse((coresb['X_IMAGE'][i], coresb['Y_IMAGE'][i]),
    #                              coresb['ella'][i] * 2, coresb['ellb'][i] * 2,
    #                              angle=coresb['ellt'][i],
    #                              linewidth=linewidth / 2,
    #                              fill=False, zorder=3,
    #                              edgecolor=(0.3, 0.3, 0.3, 0.3),
    #                              # facecolor=(1, 1, 0.0, 0.8),
    #                              path_effects=[PathEffects.withStroke(linewidth=linewidth * 0.5,
    #                                                                   foreground="w")])

    #         ax.add_patch(e1)
    return num, bnum


fitsfile = '../data/img_006.fits'
maintext = 'SgrB2 @ 6 GHz'
textcolor = (1, 1, 1, 1)
texta = ' Sources'
typetext = " UCHii"

plt.rcParams['figure.dpi'] = 75.
plt.rcParams['savefig.dpi'] = 300.
plt.rcParams['axes.labelsize'] = 9
plt.rcParams['axes.titlesize'] = 9
plt.rcParams['xtick.labelsize'] = 9
plt.rcParams['ytick.labelsize'] = 9
plt.rcParams['font.family'] = 'sans-serif'
print(plt.rcParams['font.sans-serif'])
plt.rcParams['font.sans-serif'] = ['Computer Modern Sans Serif']
plt.clf()
tick_fontsize = 9

fig = plt.figure(figsize=(10, 9))

gs = gridspec.GridSpec(2, 2, width_ratios=[1, 1])
plt.subplots_adjust(wspace=0.05, hspace=0.05)
# gs.update(wspace=0., hspace=0.01)

hdu = fits.open(fitsfile)[0]

mywcs = wcs.WCS(hdu.header).celestial
bl, tr = (coordinates.SkyCoord("17:47:30",
                               "-28:26:00",
                               unit=(u.h, u.deg),
                               frame='fk5'),
          coordinates.SkyCoord("17:47:10",
                               "-28:20:30",
                               unit=(u.h, u.deg),
                               frame='fk5'))
(zx1, zy1), (zx2, zy2) = (mywcs.wcs_world2pix([[bl.ra.deg,
                                                bl.dec.deg]], 0)[0],
                          mywcs.wcs_world2pix([[tr.ra.deg,
                                                tr.dec.deg]], 0)[0])
ax0 = plt.subplot(gs[0, 0], projection=mywcs)
ax0.set_xlim(zx1, zx2)
ax0.set_ylim(zy1, zy2)

im = ax0.imshow(hdu.data * 1e3,
                transform=ax0.get_transform(mywcs),
           vmin=-5,
           vmax=10,
                cmap=plt.cm.Greys,
                interpolation='nearest',
                origin='lower',
                norm=asinh_norm.AsinhNorm())

ra = ax0.coords[0]
dec = ax0.coords[1]
ra.set_major_formatter('hh:mm:ss')
dec.set_major_formatter('dd:mm:ss')
ra.ticklabels.set_fontsize(tick_fontsize)
dec.ticklabels.set_fontsize(tick_fontsize)
ra.set_ticks_position('all')
ra.set_ticklabel_position('b')
ra.set_axislabel_position('b')
dec.set_ticks_position('all')
dec.set_ticklabel_position('l')
dec.set_axislabel_position('l')
ra.set_ticks_visible(True)
dec.set_ticks_visible(True)
ra.set_axislabel('RA (J2000)', minpad=0.9)
dec.set_axislabel('Dec (J2000)', minpad=-0.4)


ax0.text((zx2 - zx1) * 0.05 + zx1,
         (zy2 - zy1) * 0.92 + zy1,
         maintext,
         fontsize=11,
         ha='left',
         color=textcolor)


coresa = pd.read_csv('006.csv')
coresb = pd.read_csv('096.csv')

# print(list(coresa.columns.values))
# corenum, t1corenum = plotcores(ax0, coresa, coresb, linewidth=0.5)
t1corenum = 0

df = pd.read_csv('006.csv')
df2 = pd.read_csv('006.csv')
df['t'][df['gasn']<0] = np.nan
df2['t'][df['gasn']>0] = np.nan

corenum = df.shape[0]
im_sc = ax0.scatter(df['x_img'], df['y_img'],
                    c=np.log10(df['t']),
                    s=60,
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )
ax0.scatter(df2['x_img'], df2['y_img'],
                    c=np.log10(df2['t']),
                    s=60,
                    marker = '^',
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )

ax0.text((zx2 - zx1) * 0.95 + zx1,
         (zy2 - zy1) * 0.10 + zy1,
         str(corenum) + texta,
         fontsize=9,
         ha='right',
         color=(1, 1, 1.0, 1.0))

# ax0.text((zx2 - zx1) * 0.95 + zx1,
#          (zy2 - zy1) * 0.03 + zy1,
#          str(t1corenum) + typetext,
#          fontsize=9,
#          ha='right',
#          color=(1, 1, 1.0, 1.0),
#          path_effects=[PathEffects.withStroke(linewidth=1.3,
#                                               foreground="b")])

beamstr = '$(%4.2f^{\\prime\\prime},\\ %4.2f^{\\prime\\prime},\\ %4.1f^{\\circ})$' % (hdu.header['BMAJ'] * 3600,
                                                                                      hdu.header['BMIN'] *
                                                                                      3600,
                                                                                      hdu.header['BPA'])
beamstr = '(%4.2f", %4.2f", %4.1f°)' % (hdu.header['BMAJ'] * 3600,
                                        hdu.header['BMIN'] * 3600,
                                        hdu.header['BPA'])
ax0.text((zx2 - zx1) * 0.03 + zx1,
         (zy2 - zy1) * 0.02 + zy1,
         beamstr,
         fontsize=9,
         ha='left',
         color=textcolor)


def region_anno(ax, physcoor, txtcoor, text):
    sgrb2s_coor = coordinates.SkyCoord(physcoor[0],
                                       physcoor[1],
                                       unit=(u.h, u.deg),
                                       frame='fk5')
    sgrb2s_x, sgrb2s_y = mywcs.wcs_world2pix([[sgrb2s_coor.ra.deg,
                                               sgrb2s_coor.dec.deg]],
                                             0)[0]
    sgrb2s_txt_coor = coordinates.SkyCoord(txtcoor[0],
                                           txtcoor[1],
                                           unit=(u.h, u.deg),
                                           frame='fk5')
    sgrb2s_txt_x, sgrb2s_txt_y = mywcs.wcs_world2pix([[sgrb2s_txt_coor.ra.deg,
                                                       sgrb2s_txt_coor.dec.deg]],
                                                     0)[0]
    anno = ax0.annotate(text, xy=(sgrb2s_x, sgrb2s_y),
                        xytext=(sgrb2s_txt_x, sgrb2s_txt_y),
                        color='w',
                        arrowprops=dict(edgecolor='w',
                                        arrowstyle='-', linewidth=0.8),
                        path_effects=[PathEffects.withStroke(linewidth=2,
                                                             foreground="k")])
    anno.arrow_patch.set_path_effects([
        PathEffects.Stroke(linewidth=2, foreground="k"),
        PathEffects.Normal()])
    return 0


if 1:
    region_anno(ax=ax0,
                physcoor=["17:47:20.5", "-28:23:06"],
                txtcoor=["17:47:24.0", "-28:23:10"],
                text='M')
    region_anno(ax=ax0,
                physcoor=["17:47:20.2", "-28:22:21"],
                txtcoor=["17:47:16.5", "-28:21:50"],
                text='N')
    region_anno(ax=ax0,
                physcoor=["17:47:20.430", "-28:23:45.06"],
                txtcoor=["17:47:17.5", "-28:23:55"],
                text='S')
    region_anno(ax=ax0,
                physcoor=["17:47:21.0", "-28:25:10"],
                txtcoor=["17:47:18", "-28:25:10"],
                text='DS')
    region_anno(ax=ax0,
                physcoor=["17:47:19.3", "-28:24:38"],
                txtcoor=["17:47:17", "-28:24:20"],
                text='AA')
    region_anno(ax=ax0,
                physcoor=["17:47:13.0", "-28:24:40"],
                txtcoor=["17:47:12", "-28:24:20"],
                text='V')
# # ================ SgrB2 M =================
# sgrb2m_coor = coordinates.SkyCoord("17:47:20.5",
#                                    "-28:23:06",
#                                    unit=(u.h, u.deg),
#                                    frame='fk5')
# sgrb2m_x, sgrb2m_y = mywcs.wcs_world2pix([[sgrb2m_coor.ra.deg,
#                                            sgrb2m_coor.dec.deg]],
#                                          0)[0]
# sgrb2m_txt_coor = coordinates.SkyCoord("17:47:23.0",
#                                        "-28:23:20",
#                                        unit=(u.h, u.deg),
#                                        frame='fk5')
# sgrb2m_txt_x, sgrb2m_txt_y = mywcs.wcs_world2pix([[sgrb2m_txt_coor.ra.deg,
#                                                    sgrb2m_txt_coor.dec.deg]],
#                                                  0)[0]
# anno = ax0.annotate('M', xy=(sgrb2m_x, sgrb2m_y),
#                     xytext=(sgrb2m_txt_x, sgrb2m_txt_y),
#                     color=textcolor,
#                     arrowprops=dict(edgecolor=textcolor,
#                                     arrowstyle='-', linewidth=1))
# # ================ SgrB2 N =================
# sgrb2n_coor = coordinates.SkyCoord("17:47:20.2",
#                                    "-28:22:21",
#                                    unit=(u.h, u.deg),
#                                    frame='fk5')
# sgrb2n_x, sgrb2n_y = mywcs.wcs_world2pix([[sgrb2n_coor.ra.deg,
#                                            sgrb2n_coor.dec.deg]],
#                                          0)[0]
# sgrb2n_txt_coor = coordinates.SkyCoord("17:47:23",
#                                        "-28:22:30",
#                                        unit=(u.h, u.deg),
#                                        frame='fk5')
# sgrb2n_txt_x, sgrb2n_txt_y = mywcs.wcs_world2pix([[sgrb2n_txt_coor.ra.deg,
#                                                    sgrb2n_txt_coor.dec.deg]],
#                                                  0)[0]
# anno = ax0.annotate('N', xy=(sgrb2n_x, sgrb2n_y),
#                     xytext=(sgrb2n_txt_x, sgrb2n_txt_y),
#                     color=textcolor,
#                     arrowprops=dict(edgecolor=textcolor,
#                                     arrowstyle='-', linewidth=1))
# # ================ SgrB2 S =================
# sgrb2s_coor = coordinates.SkyCoord("17:47:20.430",
#                                    "-28:23:45.06",
#                                    unit=(u.h, u.deg),
#                                    frame='fk5')
# sgrb2s_x, sgrb2s_y = mywcs.wcs_world2pix([[sgrb2s_coor.ra.deg,
#                                            sgrb2s_coor.dec.deg]],
#                                          0)[0]
# sgrb2s_txt_coor = coordinates.SkyCoord("17:47:23",
#                                        "-28:23:55",
#                                        unit=(u.h, u.deg),
#                                        frame='fk5')
# sgrb2s_txt_x, sgrb2s_txt_y = mywcs.wcs_world2pix([[sgrb2s_txt_coor.ra.deg,
#                                                    sgrb2s_txt_coor.dec.deg]],
#                                                  0)[0]
# anno = ax0.annotate('S', xy=(sgrb2s_x, sgrb2s_y),
#                     xytext=(sgrb2s_txt_x, sgrb2s_txt_y),
#                     color=textcolor,
#                     arrowprops=dict(edgecolor=textcolor,
#                                     arrowstyle='-', linewidth=1))

scalebarpos = coordinates.SkyCoord(
    "17:47:27", "-28:25:30", unit=(u.h, u.deg), frame='fk5')
scalebarlen = (2 * u.pc / distance).to(u.arcsec,
                                       u.dimensionless_angles())

make_scalebar(ax0, scalebarpos,
              length=scalebarlen,
              color=textcolor,
              label='50" 2 pc',
              text_offset=1.0 * u.arcsec,
              fontsize=8
              )
ra.set_ticks(size=-3, color='w')
dec.set_ticks(size=-3, color='w')

# cbar_ax = fig.add_axes(
#         [0.7, 0.11, 0.01, 0.51])

# cb = plt.colorbar(im, cax=cbar_ax, orientation='vertical')
# cbar_ax.yaxis.set_ticks_position("right")
# cbar_ax.yaxis.set_label_position('right')
# cbar_ax.tick_params(axis='both', which='both', direction='in')
# cb.set_label("$S$ [mJy beam$^{-1}$]")
# cb.ax.zorder = 1e8


def subplot(mygs=gs[0, 1],
            wcs=mywcs,
            mysubsize=350,
            vmin=-2,
            vmax=40,
            titletext="Sgr B2 (N)"
            ):
    ax1 = plt.subplot(mygs, projection=mywcs)
    subsize = mysubsize
    zx1 = 4480 + 300 - subsize
    zx2 = 4480 + 300 + subsize
    zy1 = 5480 + 300 - subsize
    zy2 = 5480 + 300 + subsize
    ax1.set_xlim(zx1, zx2)
    ax1.set_ylim(zy1, zy2)
    ax1.imshow(hdu.data * 1e3,
               transform=ax1.get_transform(mywcs),
               vmin=vmin,
               vmax=vmax,
               cmap=plt.cm.RdYlBu_r,
               interpolation='nearest',
               origin='lower',
               aspect='equal')
    ax1.text((zx2 - zx1) * 0.05 + zx1,
             (zy2 - zy1) * 0.93 + zy1,
             titletext,
             fontsize=9,
             ha='left',
             color=textcolor)
    return 0


for poly in polygon_reader('large_hii_regions.reg'):
    e1 = patches.Polygon(poly,
                         linewidth=0.5,
                         fill=False, zorder=29,
                         edgecolor=(1.0, 1.0, 0.5, 1.0),
                         # facecolor=(1, 1, 0.0, 0.8),
                         path_effects=[PathEffects.withStroke(linewidth=0.8,
                                                              foreground="b")])

    ax0.add_patch(e1)

    #####################################################
    ####### Subplot N ###################################


ax1 = plt.subplot(gs[0, 1], projection=mywcs)
subsize = 200
zx1 = 4820 - subsize
zx2 = 4820 + subsize
zy1 = 5750 - subsize
zy2 = 5750 + subsize
ax1.set_xlim(zx1, zx2)
ax1.set_ylim(zy1, zy2)

ax1.imshow(hdu.data * 1e3,
           transform=ax1.get_transform(mywcs),
           vmin=-5,
           vmax=10,
           cmap=plt.cm.Greys,
           interpolation='nearest',
           origin='lower',
           aspect='equal',
           norm=asinh_norm.AsinhNorm())


ax1.text((zx2 - zx1) * 0.05 + zx1,
         (zy2 - zy1) * 0.93 + zy1,
         "Sgr B2 (N)",
         fontsize=9,
         ha='left',
         color=textcolor)


corenum, t1corenum = plotcores(ax1, coresa, coresb, linewidth=0.5)

im_sc = ax1.scatter(df['x_img'], df['y_img'],
                    c=np.log10(df['t']),
                    s=60,
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )
ax1.scatter(df2['x_img'], df2['y_img'],
                    c=np.log10(df2['t']),
                    s=60,
                    marker = '^',
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )

ax1.text((zx2 - zx1) * 0.95 + zx1,
         (zy2 - zy1) * 0.10 + zy1,
         str(corenum) + texta,
         fontsize=9,
         ha='right',
         color=(1, 1, 1.0, 1.0))

# ax1.text((zx2 - zx1) * 0.95 + zx1,
#          (zy2 - zy1) * 0.03 + zy1,
#          str(t1corenum) + typetext,
#          fontsize=9,
#          ha='right',
#          color=(1, 1, 1.0, 1.0),
#          path_effects=[PathEffects.withStroke(linewidth=1.3,
#                                               foreground="b")])


ax1.set_xticks([])
ax1.set_yticks([])
ax1.yaxis.set_label_position("right")
ax1.yaxis.set_ticks_position("right")
ax1.set_xticklabels('')
ax1.set_yticklabels('')

ax0.add_patch(patches.Rectangle(((zx1+zx2)/2 - subsize, (zy1+zy2)/2 - subsize),
                                subsize * 2, subsize * 2,
                                fill=False,
                                linestyle='--',
                                linewidth=1.2,
                                edgecolor='#FFFFFF'))

# con = ConnectionPatch(xyA=(4780 - subsize, 5780 - subsize),
#                       xyB=(4780 - subsize, 5780 - subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax1,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# con = ConnectionPatch(xyA=(4780 - subsize, 5780 + subsize),
#                       xyB=(4780 - subsize, 5780 + subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax1,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# scalebarpos = coordinates.SkyCoord(
#     "17:47:20.74", "-28:22:31.635", unit=(u.h, u.deg), frame='fk5')
# scalebarlen = (0.2 * u.pc / distance).to(u.arcsec,
#                                          u.dimensionless_angles())

# make_scalebar(ax1, scalebarpos,
#               length=scalebarlen,
#               color=textcolor,
#               label='5" 0.2 pc',
#               text_offset=1.0 * u.arcsec,
#               fontsize=8
#               )
ra = ax1.coords[0]
dec = ax1.coords[1]
ra.set_ticklabel_visible(False)
dec.set_ticklabel_visible(False)
ra.set_ticks_visible(False)
dec.set_ticks_visible(False)

for poly in polygon_reader('large_hii_regions.reg'):
    e1 = patches.Polygon(poly,
                         linewidth=0.5,
                         fill=False, zorder=29,
                         edgecolor=(1.0, 1.0, 0.5, 1.0),
                         # facecolor=(1, 1, 0.0, 0.8),
                         path_effects=[PathEffects.withStroke(linewidth=0.8,
                                                              foreground="b")])

    ax1.add_patch(e1)


#####################################################
####### Subplot M ###################################

ax2 = plt.subplot(gs[1, 1], projection=mywcs)
zx1 = 4800 - 400
zx2 = 4800 + 400
zy1 = 5000 - 400
zy2 = 5000 + 400

ax2.set_xlim(zx1, zx2)
ax2.set_ylim(zy1, zy2)

ax3x1 = 4400 + 300 - 120
ax3x2 = 4400 + 300 + 120
ax3y1 = 4560 + 270 - 120
ax3y2 = 4560 + 270 + 120

ax2.add_patch(patches.Rectangle(((ax3x1+ax3x2)/2 - 120, (ax3y1+ax3y2)/2 - 120),
                                120 * 2, 120 * 2,
                                fill=False,
                                linestyle='--',
                                linewidth=1.2,
                                edgecolor='#FFFFFF'))


ax2.imshow(hdu.data * 1e3,
           transform=ax2.get_transform(mywcs),
           vmin=-5,
           vmax=10,
           cmap=plt.cm.Greys,
           interpolation='nearest',
           origin='lower',
           aspect='equal',
           norm=asinh_norm.AsinhNorm())


ax2.text((zx2 - zx1) * 0.05 + zx1,
         (zy2 - zy1) * 0.93 + zy1,
         "Sgr B2 (M)",
         fontsize=9,
         ha='left',
         color=textcolor)

corenum, t1corenum = plotcores(ax2, coresa, coresb, linewidth=0.5)

im_sc = ax2.scatter(df['x_img'], df['y_img'],
                    c=np.log10(df['t']),
                    s=60,
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )
ax2.scatter(df2['x_img'], df2['y_img'],
                    c=np.log10(df2['t']),
                    s=60,
                    marker = '^',
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )

ax2.text((zx2 - zx1) * 0.95 + zx1,
         (zy2 - zy1) * 0.10 + zy1,
         str(corenum) + texta,
         fontsize=9,
         ha='right',
         color=(1, 1, 1.0, 1.0))

# ax2.text((zx2 - zx1) * 0.95 + zx1,
#          (zy2 - zy1) * 0.03 + zy1,
#          str(t1corenum) + typetext,
#          fontsize=9,
#          ha='right',
#          color=(1, 1, 1.0, 1.0),
#          path_effects=[PathEffects.withStroke(linewidth=1.3,
#                                               foreground="b")])


ax2.set_xticks([])
ax2.set_yticks([])
ax2.yaxis.set_label_position("right")
ax2.yaxis.set_ticks_position("right")
ax2.set_xticklabels('')
ax2.set_yticklabels('')

ax0.add_patch(patches.Rectangle(((zx1 + zx2)/2, (zy1 + zy2)/2),
                                (zx1 - zx2), (zy1 - zy2),
                                fill=False,
                                linestyle='--',
                                linewidth=1.2,
                                edgecolor='#FFFFFF'))

# con = ConnectionPatch(xyA=(4700 - subsize, 4860 - subsize),
#                       xyB=(4700 - subsize, 4860 - subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax2,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# con = ConnectionPatch(xyA=(4700 - subsize, 4860 + subsize),
#                       xyB=(4700 - subsize, 4860 + subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax2,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# scalebarpos = coordinates.SkyCoord(
#     "17:47:21", "-28:23:19.263", unit=(u.h, u.deg), frame='fk5')
# scalebarlen = (0.2 * u.pc / distance).to(u.arcsec,
#                                          u.dimensionless_angles())

# make_scalebar(ax2, scalebarpos,
#               length=scalebarlen,
#               color=textcolor,
#               label='5" 0.2 pc',
#               text_offset=1.0 * u.arcsec,
#               fontsize=8
#               )

ra = ax2.coords[0]
dec = ax2.coords[1]
ra.set_ticklabel_visible(False)
dec.set_ticklabel_visible(False)
ra.set_ticks_visible(False)
dec.set_ticks_visible(False)

for poly in polygon_reader('large_hii_regions.reg'):
    e1 = patches.Polygon(poly,
                         linewidth=0.5,
                         fill=False, zorder=29,
                         edgecolor=(1.0, 1.0, 0.5, 1.0),
                         # facecolor=(1, 1, 0.0, 0.8),
                         path_effects=[PathEffects.withStroke(linewidth=0.8,
                                                              foreground="b")])

    ax2.add_patch(e1)


#####################################################
####### Subplot M ###################################

ax3 = plt.subplot(gs[1, 0], projection=mywcs)
zx1 = 4400 + 300 - 120
zx2 = 4400 + 300 + 120
zy1 = 4560 + 270 - 120
zy2 = 4560 + 270 + 120

ax3.set_xlim(zx1, zx2)
ax3.set_ylim(zy1, zy2)

ax0.add_patch(patches.Rectangle(((zx1 + zx2)/2, (zy1 + zy2)/2),
                                (zx1 - zx2), (zy1 - zy2),
                                fill=False,
                                linestyle='--',
                                linewidth=1.2,
                                edgecolor='#FFFFFF'))

ax3.imshow(hdu.data * 1e3,
           transform=ax3.get_transform(mywcs),
           vmin=-5,
           vmax=10,
           cmap=plt.cm.Greys,
           interpolation='nearest',
           origin='lower',
           aspect='equal',
           norm=asinh_norm.AsinhNorm())


ax3.text((zx2 - zx1) * 0.05 + zx1,
         (zy2 - zy1) * 0.93 + zy1,
         "Sgr B2 (M)",
         fontsize=9,
         ha='left',
         color=textcolor)

corenum, t1corenum = plotcores(ax3, coresa, coresb, linewidth=0.5)

im_sc = ax3.scatter(df['x_img'], df['y_img'],
                    c=np.log10(df['t']),
                    s=60,
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )
ax3.scatter(df2['x_img'], df2['y_img'],
                    c=np.log10(df2['t']),
                    s=60,
                    marker = '^',
                    cmap=plt.cm.jet,
                    edgecolor = 'w',
                    vmin = 3.8,
                    vmax = 5.3
                    )

ax3.text((zx2 - zx1) * 0.95 + zx1,
         (zy2 - zy1) * 0.10 + zy1,
         str(corenum) + texta,
         fontsize=9,
         ha='right',
         color=(1, 1, 1.0, 1.0))

# ax3.text((zx2 - zx1) * 0.95 + zx1,
#          (zy2 - zy1) * 0.03 + zy1,
#          str(t1corenum) + typetext,
#          fontsize=9,
#          ha='right',
#          color=(1, 1, 1.0, 1.0),
#          path_effects=[PathEffects.withStroke(linewidth=1.3,
#                                               foreground="b")])


ax3.set_xticks([])
ax3.set_yticks([])
ax3.yaxis.set_label_position("right")
ax3.yaxis.set_ticks_position("right")
ax3.set_xticklabels('')
ax3.set_yticklabels('')

# ax0.add_patch(patches.Rectangle((4700 - subsize, 4860 - subsize),
#                                 subsize * 2, subsize * 2,
#                                 fill=False,
#                                 linestyle='--',
#                                 linewidth=1.2,
#                                 edgecolor='#FFFFFF'))

# con = ConnectionPatch(xyA=(4700 - subsize, 4860 - subsize),
#                       xyB=(4700 - subsize, 4860 - subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax3,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# con = ConnectionPatch(xyA=(4700 - subsize, 4860 + subsize),
#                       xyB=(4700 - subsize, 4860 + subsize),
#                       coordsA="data",
#                       coordsB="data",
#                       axesA=ax0,
#                       axesB=ax3,
#                       color='#FFFFFF',
#                       zorder=1000,
#                       linewidth=1.0)
# ax0.add_artist(con)

# scalebarpos = coordinates.SkyCoord(
#     "17:47:20", "-28:23:19.263", unit=(u.h, u.deg), frame='fk5')
# scalebarlen = (0.2 * u.pc / distance).to(u.arcsec,
#                                          u.dimensionless_angles())

# make_scalebar(ax3, scalebarpos,
#               length=scalebarlen,
#               color=textcolor,
#               label='5" 0.2 pc',
#               text_offset=1.0 * u.arcsec,
#               fontsize=8
#               )

ra = ax3.coords[0]
dec = ax3.coords[1]
ra.set_ticklabel_visible(False)
dec.set_ticklabel_visible(False)
ra.set_ticks_visible(False)
dec.set_ticks_visible(False)

for poly in polygon_reader('large_hii_regions.reg'):
    e1 = patches.Polygon(poly,
                         linewidth=0.5,
                         fill=False, zorder=29,
                         edgecolor=(1.0, 1.0, 0.5, 1.0),
                         # facecolor=(1, 1, 0.0, 0.8),
                         path_effects=[PathEffects.withStroke(linewidth=0.8,
                                                              foreground="b")])

    ax3.add_patch(e1)






# plt.subplots_adjust(bottom=0.1, right=0.8, top=0.9)
# pcbar = ax0.get_position().get_points().flatten()
plt.subplots_adjust(hspace=0.05)
pcbar0 = ax1.get_position().get_points().flatten()
pcbar = ax2.get_position().get_points().flatten()
cbar_ax = fig.add_axes(
    [pcbar[2] + 0.01 * (pcbar[2] - pcbar[0]),
     pcbar[1],
     0.02,
     pcbar0[3] - pcbar[1]])
# cbar_ax =  plt.axes([0.95, 0.4, 0.035, 0.6])
cb = plt.colorbar(im_sc, cax=cbar_ax, orientation='vertical')
cbar_ax.yaxis.set_ticks_position('right')
cbar_ax.yaxis.set_label_position('right')
cbar_ax.tick_params(axis='both', which='both', direction='in')
cb.set_label("log(Expansion Time) [yr]")


plt.savefig('../plot/time_distribution.pdf', bbox_inches='tight')
plt.clf()
